# Generated by Django 4.1.5 on 2023-02-06 02:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DateActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDrugUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TobaccoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='profile',
            name='alcohol_usage',
            field=models.ManyToManyField(null=True, to='users.alcoholusage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_activities',
            field=models.ManyToManyField(null=True, to='users.dateactivities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.ManyToManyField(null=True, to='users.diet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(null=True, to='users.education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_plans',
            field=models.ManyToManyField(null=True, to='users.familyplans'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ManyToManyField(null=True, to='users.genders'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(null=True, to='users.hobbies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(null=True, to='users.interests'),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.ManyToManyField(null=True, to='users.lookingfor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_drug_usage',
            field=models.ManyToManyField(null=True, to='users.otherdrugusage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.ManyToManyField(null=True, to='users.relationshipstatus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tobacco_usage',
            field=models.ManyToManyField(null=True, to='users.tobaccousage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weed_usage',
            field=models.ManyToManyField(null=True, to='users.weedusage'),
        ),
    ]
