# Generated by Django 4.1.5 on 2023-02-06 02:54

from django.db import migrations
from users.models import AlcoholUsage, Diet, FamilyPlans, Genders, LookingFor, OtherDrugUsage
from users.models import RelationshipStatus, TobaccoUsage, WeedUsage

def add_alcohol_usage(apps, schema_editor):
    AlcoholUsage.objects.bulk_create([
        AlcoholUsage(usage='Not for me'),
        AlcoholUsage(usage='Sober'),
        AlcoholUsage(usage='Somewhat sober'),
        AlcoholUsage(usage='On special occasions'),
        AlcoholUsage(usage='Socially'),
        AlcoholUsage(usage='Often'),
    ])

def delete_alcohol_usage(apps, schema_editor):
    AlcoholUsage.objects.all().delete()    

def add_relationship_statuses(apps, schema_editor):
    RelationshipStatus.objects.bulk_create([
        RelationshipStatus( relationship='Single'),
        RelationshipStatus(relationship='In love'),
        RelationshipStatus(relationship='Engaged'),
        RelationshipStatus(relationship='Married'),
        RelationshipStatus(relationship='Divorced'),
        RelationshipStatus(relationship='Widowed'),
        RelationshipStatus(relationship='Separated'),
        RelationshipStatus(relationship='Polyamorous'),

    ])

def add_diet(apps, schema_editor):
    Diet.objects.bulk_create([
        Diet(diet='Vegetarian'),
        Diet(diet='Vegan'),
        Diet(diet='Halal'),
        Diet(diet='Kosher'),
        Diet(diet='Carnivore'),
        Diet(diet='Pescatarian'),
        Diet(diet='Dairy-free'),
        Diet(diet='Other'),
        Diet(diet='I eat everything'),
    ])

def delete_diet(apps, schema_editor):
    Diet.objects.all().delete()

def delete_relationship_statuses(apps, schema_editor):
    RelationshipStatus.objects.all().delete()

def add_family_plans(apps, schema_editor):
    FamilyPlans.objects.bulk_create([
        FamilyPlans(plan='Wants Children'),
        FamilyPlans(plan="Doesn't want children"),
        FamilyPlans(plan="Has Children and wants more"),
        FamilyPlans(plan="Has Children and doesn't want more"),
        FamilyPlans(plan='Not sure'),
    ])


def delete_family_plans(apps, schema_editor):
    FamilyPlans.objects.all().delete()

def add_genders(apps, schema_editor):
    Genders.objects.bulk_create([
        Genders(gender='Male'),
        Genders(gender='Female'),
        Genders(gender='Transman'),
        Genders(gender='Transwoman'),
        Genders(gender='Non-binary'),
        Genders(gender='Other'),
    ])

def delete_genders(apps, schema_editor):
    Genders.objects.all().delete()

def add_looking_for(apps, schema_editor):
    LookingFor.objects.bulk_create([
        LookingFor(option='Woman'),
        LookingFor(option='Man'),
        LookingFor(option='Transman'),
        LookingFor(option='Transwoman'),
        LookingFor(option='Non-binary'),
        LookingFor(option='Other'),
    ])

def delete_looking_for(apps, schema_editor):
    LookingFor.objects.all().delete()

def add_other_drug_usage(apps, schema_editor):
    OtherDrugUsage.objects.bulk_create([
        OtherDrugUsage(usage='Yes'),
        OtherDrugUsage(usage='Ocassionally'),
        OtherDrugUsage(usage='Socially'),
        OtherDrugUsage(usage='Never'),
    ])

def delete_other_drug_usage(apps, schema_editor):
    OtherDrugUsage.objects.all().delete()

def add_tobacco_usage(apps, schema_editor):
    TobaccoUsage.objects.bulk_create([
        TobaccoUsage(usage='Social smoker'),
        TobaccoUsage(usage='Smoker when drinking'),
        TobaccoUsage(usage='Non-smoker'),
        TobaccoUsage(usage='Smoker'),
        TobaccoUsage(usage='Trying to quit'),
    ])

def delete_tobacco_usage(apps, schema_editor):
    TobaccoUsage.objects.all().delete()

def add_weed_usage(apps, schema_editor):
    WeedUsage.objects.bulk_create([
        WeedUsage(usage='Yes'),
        WeedUsage(usage='Occasionally'),
        WeedUsage(usage='Socially'),
        WeedUsage(usage='Never'),
    ])

def delete_weed_usage(apps, schema_editor):
    WeedUsage.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alcoholusage_dateactivities_diet_education_and_more'),
    ]

    operations = [
        migrations.RunPython(add_relationship_statuses, delete_relationship_statuses),
        migrations.RunPython(add_alcohol_usage, delete_alcohol_usage),
        migrations.RunPython(add_diet, delete_diet),
        migrations.RunPython(add_family_plans, delete_family_plans),
        migrations.RunPython(add_genders, delete_genders),
        migrations.RunPython(add_looking_for, delete_looking_for),
        migrations.RunPython(add_other_drug_usage, delete_other_drug_usage),
        migrations.RunPython(add_tobacco_usage, delete_tobacco_usage),
        migrations.RunPython(add_weed_usage, delete_weed_usage),
    ]
