# Generated by Django 4.1.5 on 2023-02-08 09:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230206_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alcohol_usage',
            field=models.ManyToManyField(blank=True, to='users.alcoholusage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_activities',
            field=models.ManyToManyField(blank=True, to='users.dateactivities'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.ManyToManyField(blank=True, to='users.diet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='users.education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_plans',
            field=models.ManyToManyField(blank=True, to='users.familyplans'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ManyToManyField(blank=True, to='users.genders'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='users.hobbies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.ManyToManyField(blank=True, to='users.lookingfor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_drug_usage',
            field=models.ManyToManyField(blank=True, to='users.otherdrugusage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.ManyToManyField(blank=True, to='users.relationshipstatus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tobacco_usage',
            field=models.ManyToManyField(blank=True, to='users.tobaccousage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weed_usage',
            field=models.ManyToManyField(blank=True, to='users.weedusage'),
        ),
    ]
