# Generated by Django 4.1.5 on 2023-02-08 18:20

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('ourdate_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='POINT(37.7749 122.419)', max_length=63),
        ),
    ]
