# Generated by Django 4.1.5 on 2023-02-09 04:09

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('ourdate_events', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='POINT(37.7749, -122.419)', max_length=63),
        ),
    ]
