# Generated by Django 4.1.5 on 2023-02-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourdate_events', '0004_event_registration_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
